# Generated by Django 4.1 on 2022-08-09 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availableDate', models.DateField()),
                ('availableStarttime', models.DateField()),
                ('availableEndtime', models.DateField()),
                ('meetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meetings')),
            ],
        ),
    ]
