# Generated by Django 4.1 on 2022-08-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_alter_meetings_meethead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='meetTime',
            field=models.DateField(blank=True),
        ),
    ]
