# Generated by Django 4.1 on 2022-08-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_alter_meetings_meettime'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='meetPurpose',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
