# Generated by Django 4.1 on 2022-08-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='그룹을 자랑해주세요!'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=40, verbose_name='그룹 이름이 무엇인가요?'),
        ),
        migrations.AlterField(
            model_name='group',
            name='purpose',
            field=models.TextField(blank=True, null=True, verbose_name='그룹 목적은요?'),
        ),
    ]
