# Generated by Django 4.1 on 2022-08-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_introduction_alter_group_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='그룹 소개'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=40, verbose_name='그룹명'),
        ),
        migrations.AlterField(
            model_name='group',
            name='purpose',
            field=models.TextField(blank=True, null=True, verbose_name='그룹 목적'),
        ),
    ]
