# Generated by Django 4.1 on 2022-08-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('남성', '남성'), ('여성', '여성'), ('선택안함', '선택안함')], max_length=10, verbose_name='성별'),
        ),
    ]
