# Generated by Django 4.1 on 2022-08-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth',
            field=models.CharField(max_length=10, null=True, verbose_name='인증번호'),
        ),
    ]
